# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['SWIFT_VERSION'] = '3.0'
#       config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
#     end
#   end
# end

target 'WatchIt' do
  pod 'Moya-ModelMapper', '4.0.0-beta.2'
  pod 'Moya', '8.0.0-beta.3'
  pod 'RxOptional'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'

  # pod 'RxCocoa', '3.0.0-beta.1'
  # pod 'RxSwift', '3.0.0-beta.1'
  # pod 'Moya', '8.0.0-beta.2'
  # pod 'Moya-ModelMapper/RxSwift'
  # #pod "Moya/RxSwift", :git => "https://github.com/Moya/Moya", :branch => "swift-3.0"


end
